Chapter 01

# 一维数组
《线性代数》 | 鸢尾花书：数学不难

本代码首先导入了用于数值计算的 NumPy 库，目的是利用其高效的数组操作功能。数学上，我们可以把数据看作一个向量，这里定义的 Python 列表  
$$a\_list = [1,\,2,\,3,\,4,\,5,\,6,\,7,\,8,\,9,\,10]$$  
包含 $10$ 个元素。接下来，利用 NumPy 的 array 函数将这个列表转换为一个一维数组，我们将其视为一个行向量，记作  
$$a = [1,\; 2,\; 3,\; 4,\; 5,\; 6,\; 7,\; 8,\; 9,\; 10].$$  

数组的维数由属性 $a.ndim$ 得到，此处 $dim = 1$，表明这是一个一维向量。数组的形状由 $a.shape$ 给出，返回值为 $(10,)$，说明行向量在其唯一的维度上共有 $10$ 个元素。

在索引部分，代码展示了如何访问行向量中的特定元素。注意在 NumPy 中采用零索引法，即第一个元素的索引为 $0$。例如：  
- $a[0]$ 返回向量的第一个元素（数学上对应 $a_1$）；  
- $a[1]$ 返回第二个元素（对应数学中的 $a_2$）；  
- $a[-1]$ 返回最后一个元素（对应数学中的 $a_{10}$）；  
- $a[-2]$ 返回倒数第二个元素（对应 $a_9$）。

切片操作则用于提取向量的子部分。切片表达式采用半开区间的形式，如 $a[0:2]$ 表示从索引 $0$ 开始，直到索引 $2$（不含 $2$）的所有元素，即得到  
$$a_{\text{slice}} = [1,\; 2].$$  
同样，$a[:2]$ 是简写形式，效果相同。表达式 $a[1:]$ 则提取从索引 $1$（即数学中的 $a_2$）开始到最后的所有元素，得到  
$$a_{\text{slice}} = [2,\; 3,\; 4,\; 5,\; 6,\; 7,\; 8,\; 9,\; 10].$$  
此外，$a[-3:]$ 和 $a[7:]$ 均提取了最后 $3$ 个元素，因为索引 $7$ 对应的是第 $8$ 个元素，于是得到  
$$a_{\text{slice}} = [8,\; 9,\; 10].$$

总体来说，这段代码展示了如何从数学上定义的行向量转化为 NumPy 数组，并通过索引与切片操作实现对向量元素的访问与提取，同时强调了 Python 中零索引与数学中常见的一索引之间的差别。

## 初始化

In [1]:
# 导入NumPy库，用于数组操作和数值计算
import numpy as np

## 创建数组

In [2]:
# 定义一个包含 10 个元素的 Python 列表
a_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
# 将 Python 列表转换为 NumPy 数组
a_ = np.array(a_list)
# a_ = np.arange(1,11)

In [5]:
a_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# 获取数组的维度（即数组的轴数，1D数组的维度为1）
dim = a_.ndim
dim  # 输出数组的维度

1

In [7]:
# 获取数组的形状（即数组每个轴上的元素个数）
shape = a_.shape
shape  # 输出数组的形状

(10,)

## 索引

In [8]:
# 访问数组的第一个元素（索引从 0 开始）
a_[0]

np.int64(1)

In [9]:
# 访问数组的第二个元素
a_[1]

np.int64(2)

In [10]:
# 访问数组的最后一个元素，索引 -1 表示倒数第一个
a_[-1]

np.int64(10)

In [11]:
# 访问数组的倒数第二个元素
a_[-2]

np.int64(9)

## 切片

In [12]:
# 获取数组的前两个元素（索引范围 [0,2)）
a_[0:2]

array([1, 2])

In [13]:
# 使用简写的切片方式，获取数组的前两个元素
a_[:2]

array([1, 2])

In [14]:
# 获取从索引 1 开始的所有元素（从第二个到最后一个）
a_[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# 获取数组的最后三个元素
a_[-3:]

array([ 8,  9, 10])

In [16]:
# 获取索引 7 及之后的所有元素（即最后三个元素）
a_[7:]

array([ 8,  9, 10])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  