Chapter 02

# 矩阵加减、数乘
《线性代数，初阶》 | 鸢尾花书：数学不难

该代码主要演示了矩阵的基本运算，包括矩阵的加法、减法、数乘以及零矩阵和单位矩阵的构造。我们从数学的角度详细描述每个步骤，并用数学公式表示。

---

### **1. 初始化**
代码首先导入 `numpy` 作为数学计算库，以便处理矩阵运算。

---

### **2. 矩阵 $A$ 和 $B$ 的定义**
代码使用 `np.random.randint(0, 10, (5,8))` 生成两个 $5 \times 8$ 的随机整数矩阵 $A$ 和 $B$，其元素范围在 $[0,10)$ 之间。

设 $A$ 和 $B$ 为：
$$
A = \begin{bmatrix}
a_{1,1} & a_{1,2} & \dots & a_{1,8} \\
a_{2,1} & a_{2,2} & \dots & a_{2,8} \\
\vdots & \vdots & \ddots & \vdots \\
a_{5,1} & a_{5,2} & \dots & a_{5,8}
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
b_{1,1} & b_{1,2} & \dots & b_{1,8} \\
b_{2,1} & b_{2,2} & \dots & b_{2,8} \\
\vdots & \vdots & \ddots & \vdots \\
b_{5,1} & b_{5,2} & \dots & b_{5,8}
\end{bmatrix}
$$

其中 $a_{i,j}, b_{i,j} \in \{0,1,2,\dots,9\}$。

---

### **3. 矩阵加法**
代码计算 $A$ 和 $B$ 的矩阵加法：
$$
C = A + B
$$
即
$$
C = \begin{bmatrix}
a_{1,1} + b_{1,1} & a_{1,2} + b_{1,2} & \dots & a_{1,8} + b_{1,8} \\
a_{2,1} + b_{2,1} & a_{2,2} + b_{2,2} & \dots & a_{2,8} + b_{2,8} \\
\vdots & \vdots & \ddots & \vdots \\
a_{5,1} + b_{5,1} & a_{5,2} + b_{5,2} & \dots & a_{5,8} + b_{5,8}
\end{bmatrix}
$$
矩阵加法要求 $A$ 和 $B$ 形状相同，按 **逐元素** 相加。

---

### **4. 矩阵减法**
代码计算 $A$ 和 $B$ 的矩阵减法：
$$
D = A - B
$$
即
$$
D = \begin{bmatrix}
a_{1,1} - b_{1,1} & a_{1,2} - b_{1,2} & \dots & a_{1,8} - b_{1,8} \\
a_{2,1} - b_{2,1} & a_{2,2} - b_{2,2} & \dots & a_{2,8} - b_{2,8} \\
\vdots & \vdots & \ddots & \vdots \\
a_{5,1} - b_{5,1} & a_{5,2} - b_{5,2} & \dots & a_{5,8} - b_{5,8}
\end{bmatrix}
$$
矩阵减法与加法类似，按 **逐元素** 相减。

---

### **5. 矩阵的数乘**
代码计算 $A$ 的数乘：
$$
k \cdot A
$$
其中 $k = 2$，即：
$$
2 \times \begin{bmatrix}
a_{1,1} & a_{1,2} & \dots & a_{1,8} \\
a_{2,1} & a_{2,2} & \dots & a_{2,8} \\
\vdots & \vdots & \ddots & \vdots \\
a_{5,1} & a_{5,2} & \dots & a_{5,8}
\end{bmatrix}
=
\begin{bmatrix}
2a_{1,1} & 2a_{1,2} & \dots & 2a_{1,8} \\
2a_{2,1} & 2a_{2,2} & \dots & 2a_{2,8} \\
\vdots & \vdots & \ddots & \vdots \\
2a_{5,1} & 2a_{5,2} & \dots & 2a_{5,8}
\end{bmatrix}
$$
标量数乘就是将 $A$ 的每个元素都乘以 $2$。

此外，代码计算：
$$
0 \times A
$$
结果是一个 **全零矩阵**：
$$
\begin{bmatrix}
0 & 0 & \dots & 0 \\
0 & 0 & \dots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \dots & 0
\end{bmatrix}
$$

---

### **6. 构造零矩阵**
`np.zeros_like(A)` 生成与 $A$ 形状相同的全零矩阵：
$$
\begin{bmatrix}
0 & 0 & \dots & 0 \\
0 & 0 & \dots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \dots & 0
\end{bmatrix}
$$

---

### **7. 构造全 1 矩阵**
`np.ones_like(A)` 生成与 $A$ 形状相同的全 1 矩阵：
$$
\begin{bmatrix}
1 & 1 & \dots & 1 \\
1 & 1 & \dots & 1 \\
\vdots & \vdots & \ddots & \vdots \\
1 & 1 & \dots & 1
\end{bmatrix}
$$
这种矩阵在计算中通常用于 **元素加法的单位矩阵**，即：
$$
A + O = \begin{bmatrix}
a_{1,1} + 1 & a_{1,2} + 1 & \dots & a_{1,8} + 1 \\
a_{2,1} + 1 & a_{2,2} + 1 & \dots & a_{2,8} + 1 \\
\vdots & \vdots & \ddots & \vdots \\
a_{5,1} + 1 & a_{5,2} + 1 & \dots & a_{5,8} + 1
\end{bmatrix}
$$

---

### **总结**
1. **矩阵加法** 和 **矩阵减法** 都是 **逐元素** 计算，要求形状相同。
2. **数乘** 将矩阵的每个元素都乘以标量。
3. **零矩阵** 是所有元素为零的矩阵，通常用于初始化或作为加法的单位元。
4. **全 1 矩阵** 可以用于对矩阵所有元素进行平移（加 1）。

通过这些操作，可以构建更复杂的矩阵计算！

## 初始化

In [1]:
import numpy as np

## 定义两个相同大小的矩阵 A 和 B

In [2]:
np.random.seed(88)  # 保证每次运行生成相同的随机数
A = np.random.randint(0, 10, (5, 8))

In [3]:
A

array([[8, 0, 1, 4, 5, 1, 0, 5],
       [0, 2, 1, 4, 7, 9, 7, 7],
       [6, 6, 3, 1, 0, 8, 6, 0],
       [0, 5, 7, 5, 3, 9, 5, 3],
       [7, 3, 9, 3, 8, 5, 0, 6]])

In [4]:
B = np.random.randint(0, 10, (5, 8))

In [7]:
B

array([[4, 0, 2, 2, 5, 9, 2, 5],
       [6, 6, 1, 1, 8, 6, 1, 2],
       [1, 7, 4, 3, 6, 6, 6, 0],
       [3, 0, 8, 2, 7, 0, 9, 7],
       [2, 6, 3, 6, 8, 6, 4, 3]])

## 矩阵加法：A + B

In [8]:
matrix_addition = A + B
matrix_addition

array([[12,  0,  3,  6, 10, 10,  2, 10],
       [ 6,  8,  2,  5, 15, 15,  8,  9],
       [ 7, 13,  7,  4,  6, 14, 12,  0],
       [ 3,  5, 15,  7, 10,  9, 14, 10],
       [ 9,  9, 12,  9, 16, 11,  4,  9]])

## 矩阵减法：A - B

In [9]:
matrix_subtraction = A - B
matrix_subtraction

array([[ 4,  0, -1,  2,  0, -8, -2,  0],
       [-6, -4,  0,  3, -1,  3,  6,  5],
       [ 5, -1, -1, -2, -6,  2,  0,  0],
       [-3,  5, -1,  3, -4,  9, -4, -4],
       [ 5, -3,  6, -3,  0, -1, -4,  3]])

## 矩阵的数乘

In [10]:
k = 2 # 标量

In [11]:
matrix_scalar_multiplication = k * A
matrix_scalar_multiplication

array([[16,  0,  2,  8, 10,  2,  0, 10],
       [ 0,  4,  2,  8, 14, 18, 14, 14],
       [12, 12,  6,  2,  0, 16, 12,  0],
       [ 0, 10, 14, 10,  6, 18, 10,  6],
       [14,  6, 18,  6, 16, 10,  0, 12]])

In [ ]:
0 * A

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
np.zeros_like(A)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
np.ones_like(A)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
O = np.ones_like(A)
O

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [17]:
A

array([[8, 0, 1, 4, 5, 1, 0, 5],
       [0, 2, 1, 4, 7, 9, 7, 7],
       [6, 6, 3, 1, 0, 8, 6, 0],
       [0, 5, 7, 5, 3, 9, 5, 3],
       [7, 3, 9, 3, 8, 5, 0, 6]])

In [16]:
A + O

array([[ 9,  1,  2,  5,  6,  2,  1,  6],
       [ 1,  3,  2,  5,  8, 10,  8,  8],
       [ 7,  7,  4,  2,  1,  9,  7,  1],
       [ 1,  6,  8,  6,  4, 10,  6,  4],
       [ 8,  4, 10,  4,  9,  6,  1,  7]])

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  